### ISSUE TITLE
Please update to version 2.3.3 of your github-buttons

### ISSUE THREAD

**Issue by donaldboulton** [ntkme/react-github-btn#4]
Dark theme support.
Thanks
Donald Boulton

**Comment by ntkme** [comment]
Semver range `^2.2.10` already include 2.3.3, and current implementation is already compatible with 2.3.3.

I could release a new version that drops the old version compatibility, but it isn’t necessary.

E.g. You can update the lock file manually; or, delete the lock file then reinstall.

**Comment by donaldboulton** [comment]
Fixed lock file works perfect.
Thanks Dark is Cool
